[breaking]
name = "breaking"
color = "ff6b6b"
description = "Changes breaking backward compatibility"

[dependencies]  # standard label used by bots
name = "dependencies"
color = "0969da"
description = "Pull requests and tasks to update dependencies"

[discussion]
name = "discussion"
color = "6ee7e2"
description = "This needs more discussion."

["duplicate"]
name = "duplicate"
color = "d1d5db"
description = "This issue or pull request already exists."

# in gitea effort labels are mutually exclusive (requires using "/" as seperator)
["effort/ 0...2 S"]
name = "effort/ 0...2 S"
color = "fef3c7"
description = "A small effort is required to solve this."

["effort/ 2...5 M"]
name = "effort/ 2...5 M"
color = "fde68a"
description = "A medium effort is required to solve this."

["effort/ 5...13 L"]
name = "effort/ 5...13 L"
color = "fcd34d"
description = "A large effort is required to solve this."

["effort/13...34 XL"]
name = "effort/13...34 XL"
color = "fcd34d"
description = "A very large effort is required to solve this."

["effort/epic"]
name = "effort/epic"
color = "f59e0b"
description = "This requires an epic effort. Split it up!"

["good first issue"]   # standard label used by github
name = "good first issue"
color = "c17dcc"
description = "Tasks to pick up by newcomers"

# in gitea priority labels are mutually exclusive (requires using "/" as seperator)
["priority/high"]
name = "priority/high"
color = "f87171"
description = "This issue is urgent and important."

["priority/low"]
name = "priority/low"
color = "e3e3e3"
description = "This issue is neither urgent nor important."

[question]
name = "Question"
color = "047857"
description = "A request for help or a question."

# in gitea state labels are mutually exclusive (requires using "/" as seperator)
["state/blocked"]
name = "state/blocked"
color = "fca5a5"
description = "On hold due to another issue or missing external requirement."

["state/confirmed"]
name = "state/confirmed"
color = "d9e9ff"
description = "This will be addressed. / Bug is confirmed."

["state/invalid-wontfix"]
name = "state/invalid-wontfix"
color = "d1d5db"
description = "This is invalid or will not be worked on."

["state/needs info"]
name = "state/needs info"
color = "bbdefb"
description = "Further information is requested."

["state/needs decision"]
name = "state/needs decision"
color = "64b5f6"
description = "This needs to be decided by maintainers."

["state/needs review"]
name = "state/needs review"
color = "2196f3"
description = "This needs to be reviewed by maintainers."

# in gitea topic labels are mutually exclusive (requires using "/" as seperator)
["topic/DX"]
name = "topic/DX"
color = "cc9b25"
description = "Developer experience related like linter, code checker etc."

["topic/UI & UX"]
name = "topic/UI & UX"
color = "f5dd9d"
description = "User interface or user experience related work"

["topic/docs"]
name = "topic/docs"
color = "efeac5"
description = "Improvements or additions to documentation"

["topic/infra"]
name = "topic/infra"
color = "bcc499"
description = "Tasks related to Docker/CI etc."

["topic/security"]
name = "topic/security"
color = "e11d21"
description = "Security related"

["topic/testing"]
name = "topic/testing"
color = "92a68a"
description = "Testing related tasks"

# in gitea type labels are mutually exclusive (requires using "/" as seperator)
["type/bug"]
name = "type/bug"
color = "e11d21"
description = "Something is not working as expected."

["type/enhancement"]
name = "type/enhancement"
color = "4caf50"
description = "Request for changing or improving existing feature."

["type/feature"]
name = "type/feature"
color = "81c784"
description = "Request for adding a new feature"

["type/housekeeping"]
name = "type/housekeeping"
color = "c8e6c9"
description = "Code clean-up or maintenance tasks like updates etc."

["type/user story"]
name = "type/user story"
color = "065f46"
description = "Description of new feature from end-user perspective"
