name: Run checks

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

  pull_request:
    branches:
      - main

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - "py38"
          - "py39"
          - "py310"
          - "py311"
          - "flake8"
          - "mypy"

        include:
          - environment: "py38"
            python: "3.8"
          - environment: "py39"
            python: "3.9"
          - environment: "py310"
            python: "3.10"
          - environment: "py311"
            python: "3.11"
          - environment: "flake8"
            python: "3.11"
          - environment: "mypy"
            python: "3.11"

    container:
      image: python:${{ matrix.python }}

    steps:
      - uses: actions/checkout@master
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run tox
        run: |
          tox -e ${{ matrix.environment }}
